### ISSUE TITLE
We support Mustache spec v1.1.3 but v1.2.1 is the latest

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/pystache#4]

**Comment by sarnold** [comment]
NULL interpolation seems broken against the latest spec version; 3 Fails after the cascade of errors. Note I haven't looked at anything yet, since I just now tried it:

```
======================================================================
FAIL: Mustache spec (interpolation.yml): 'Basic Null Interpolation' (pystache.tests.spectesting._make_spec_test.<locals>.SpecTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nerdboy/src/pystache/.tox/setup/lib/python3.9/site-packages/pystache/tests/spectesting.py", line 189, in run_test
    self._runTest()
  File "/home/nerdboy/src/pystache/.tox/setup/lib/python3.9/site-packages/pystache/tests/spectesting.py", line 287, in _runTest
    self.assertString(actual, expected, format=message)
  File "/home/nerdboy/src/pystache/.tox/setup/lib/python3.9/site-packages/pystache/tests/common.py", line 160, in assertString
    self.assertEqual(actual, expected, make_message("different characters"))
AssertionError: 'I (None) be seen!' != 'I () be seen!'
- I (None) be seen!
?    ----
+ I () be seen!
 : 'Basic Null Interpolation': Nulls should interpolate as the empty string.

  File: /home/nerdboy/src/pystache/ext/spec/specs/interpolation.yml

  Template: """I ({{cannot}}) be seen!"""

  Context: {'cannot': None}

  String mismatch: different characters

        Expected: """I () be seen!"""
        Actual:   """I (None) be seen!"""

        Expected: 'I () be seen!'
        Actual:   'I (None) be seen!'

  [using yaml (version 6.0)]
```
